### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by yswheye** [JackyAndroid/AndroidChromium#2]
Caused by: java.lang.ClassCastException: com.android.tools.fd.runtime.BootstrapApplication cannot be cast to org.chromium.base.BaseChromiumApplication
                                                                                 at org.chromium.base.BaseChromiumApplication.initCommandLine(BaseChromiumApplication.java:76)
                                                                                 at org.chromium.chrome.browser.ChromeBrowserProvider.onCreate(ChromeBrowserProvider.java:267)
                                                                                 at android.content.ContentProvider.attachInfo(ContentProvider.java:1696)
                                                                                 at android.content.ContentProvider.attachInfo(ContentProvider.java:1671)
                                                                                 at android.app.ActivityThread.installProvider(ActivityThread.java:4999)
                                                                                 at android.app.ActivityThread.installContentProviders(ActivityThread.java:4594) 
                                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4534) 
                                                                                 at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:135) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by yswheye** [comment]
@JackyAndroid I can not open it

**Comment by JackyAndroid** [comment]
@yswheye If you are using AndroidStudio above 2.0 version and open instant run function, suggested to debug after closing (instant run will modify on the Application of the result in chrome provider context reference error)

**Comment by yswheye** [comment]
@JackyAndroid that's it, thank you!

**Comment by JackyAndroid** [comment]
@yswheye welcome
