### ISSUE TITLE
只能在真机上运行吗?另外流量节省程序崩溃

### ISSUE THREAD

**Issue by pananfly** [JackyAndroid/AndroidChromium#3]
以下是模拟器4.1.1报错，另外6.0直接崩溃，没有log
FATAL EXCEPTION: main
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{org.chromium.chrome.browser/org.chromium.chrome.browser.ChromeTabbedActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:130)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                     at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:340)
                                                     at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:309)
                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:273)
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                     at org.chromium.chrome.browser.ChromeActivity.setContentView(ChromeActivity.java:334)
                                                     at org.chromium.chrome.browser.init.AsyncInitializationActivity.setContentViewAndLoadLibrary(AsyncInitializationActivity.java:83)
                                                     at org.chromium.chrome.browser.init.ChromeBrowserInitializer.handlePreNativeStartup(ChromeBrowserInitializer.java:88)
                                                     at org.chromium.chrome.browser.init.AsyncInitializationActivity.onCreate(AsyncInitializationActivity.java:183)
                                                     at android.app.Activity.performCreate(Activity.java:5008)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                     at dalvik.system.NativeStart.main(Native Method) 

-------------------------分割线--------------------------------------

真机：moto g lte 魔趣6.0
设置里－流量节省程序－点击打开崩溃重启，如果首页提示打开流量节省，打开后，再到设置里，点击流量节省程序就崩溃重启。

**Comment by JackyAndroid** [comment]
正在解决相关问题，多谢反馈🙂

**Comment by JackyAndroid** [comment]
@pananfly 已解决
