### ISSUE TITLE
Chrome crash with "NoClassDefFoundError" exception--device compatibility

### ISSUE THREAD

**Issue by msahad** [JackyAndroid/AndroidChromium#31]
In some devices (Samsung tab 3) Chrome app cannot be opened. Every time it crashes with following exception.

org.chromium.chrome.browser E/AndroidRuntime: FATAL EXCEPTION: main 
Process: org.chromium.chrome.browser, PID: 15079
java.lang.NoClassDefFoundError: org.chromium.chrome.browser.provider.ChromeBrowserProvider$1 at org.chromium.chrome.browser.provider.ChromeBrowserProvider.onCreate(ChromeBrowserProvider.java:248)
     at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
     at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
     at android.app.ActivityThread.installProvider(ActivityThread.java:5221)
     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4815)
     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4698)
     at android.app.ActivityThread.access$1600(ActivityThread.java:172)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1365)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:146)
     at android.app.ActivityThread.main(ActivityThread.java:5598)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:515)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
     at dalvik.system.NativeStart.main(Native Method)

**Comment by JackyAndroid** [comment]
duplicate #2 #7

**Comment by msahad** [comment]
Instant run is already disabled. App crash even in release build. It happens only in some models like samsung tab 2 and some LG devices. In all other devices working fine.

**Comment by uplusplus** [comment]
add the follow line:

        MultiDex.install(this);

to

org.chromium.chrome.browser.ChromeApplication#attachBaseContext
