### ISSUE TITLE
Chrome crashes when trying to enter the "Data saver" option

### ISSUE THREAD

**Issue by AviFix** [JackyAndroid/AndroidChromium#33]
Hi,

The app crashes when trying to enter the "Data saver" option in the settings menu.

![image](https://cloud.githubusercontent.com/assets/3835504/25856520/e8003496-34de-11e7-8e73-0f9b10f2cb95.png)

Crash log: 
  `05-09 17:32:44.487 27871-27871/org.chromium.chrome.browser E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: org.chromium.chrome.browser, PID: 27871
                                                                             android.view.InflateException: Binary XML file line #22: Binary XML file line #6: Error inflating class org.chromium.third_party.android.datausagechart.ChartDataUsageView
                                                                             Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class org.chromium.third_party.android.datausagechart.ChartDataUsageView
                                                                             Caused by: java.lang.reflect.InvocationTargetException
                                                                                 at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                 at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                                                 at android.view.LayoutInflater.parseInclude(LayoutInflater.java:964)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                                 at android.preference.Preference.onCreateView(Preference.java:523)
                                                                                 at android.preference.Preference.getView(Preference.java:493)
                                                                                 at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:246)
                                                                                 at android.widget.AbsListView.obtainView(AbsListView.java:2371)
                                                                                 at android.widget.ListView.makeAndAddView(ListView.java:1970)
                                                                                 at android.widget.ListView.fillDown(ListView.java:704)
                                                                                 at android.widget.ListView.fillFromTop(ListView.java:765)
                                                                                 at android.widget.ListView.layoutChildren(ListView.java:1744)
                                                                                 at android.widget.AbsListView.onLayout(AbsListView.java:2170)
                                                                                 at android.view.View.layout(View.java:17637)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                 at android.view.View.layout(View.java:17637)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                 at android.view.View.layout(View.java:17637)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                 at android.view.View.layout(View.java:17637)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                 at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
                                                                                 at android.view.View.layout(View.java:17637)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                 at android.view.View.layout(View.java:17637)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                 at android.view.View.layout(View.java:17637)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                 at com.android.internal.policy.DecorView.onLayout(DecorView.java:727)
                                                                                 at android.view.View.layout(View.java:17637)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
05-09 17:32:44.488 27871-27871/org.chromium.chrome.browser E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                 at android.os.Handler.handleCallback(Handler.java:751)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                              Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/chromium/third_party/android/R$styleable;
                                                                                 at org.chromium.third_party.android.datausagechart.ChartView.<init>(ChartView.java:58)
                                                                                 at org.chromium.third_party.android.datausagechart.ChartDataUsageView.<init>(ChartDataUsageView.java:75)
                                                                                 at org.chromium.third_party.android.datausagechart.ChartDataUsageView.<init>(ChartDataUsageView.java:67)
                                                                                 	... 66 more
                                                                              Caused by: java.lang.ClassNotFoundException: Didn't find class "org.chromium.third_party.android.R$styleable" on path: DexPathList[[zip file "/data/app/org.chromium.chrome.browser-2/base.apk"],nativeLibraryDirectories=[/data/app/org.chromium.chrome.browser-2/lib/arm, /data/app/org.chromium.chrome.browser-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                 	... 69 more
05-09 17:33:14.400 27871-27982/org.chromium.chrome.browser E/chromium: [ERROR:shell_integration_android.cc(27)] Not implemented reached in shell_integration::DefaultWebClientState shell_integration::GetDefaultBrowser()
`

Thanks
Avi

**Comment by JackyAndroid** [comment]
This problem has been resolved #3

**Comment by AviFix** [comment]
Thanks
