### ISSUE TITLE
App crashes on file upload

### ISSUE THREAD

**Issue by AviFix** [JackyAndroid/AndroidChromium#34]
Hi,

If i tray to select a file via  [html file input](https://www.w3schools.com/tags/att_input_accept.asp) then the app crashes with the following error:

`05-11 15:41:48.184 11403-11436/org.chromium.chrome.browser E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
                                                                             Process: org.chromium.chrome.browser, PID: 11403
                                                                             java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                 at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                                                 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                                 at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                 at java.lang.Thread.run(Thread.java:761)
                                                                              Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                                                                                 at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:561)
                                                                                 at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:535)
                                                                                 at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:377)
                                                                                 at org.chromium.chrome.browser.FileProviderHelper.getContentUriFromFile(FileProviderHelper.java:24)
                                                                                 at org.chromium.base.ContentUriUtils.getContentUriFromFile(ContentUriUtils.java:54)
                                                                                 at org.chromium.ui.UiUtils.getUriForImageCaptureFile(UiUtils.java:332)
                                                                                 at org.chromium.ui.base.SelectFileDialog$GetCameraIntentTask.doInBackground(SelectFileDialog.java:218)
                                                                                 at org.chromium.ui.base.SelectFileDialog$GetCameraIntentTask.doInBackground(SelectFileDialog.java:213)
                                                                                 at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                                 at java.lang.Thread.run(Thread.java:761) 
`

Thanks
Avi

**Comment by AviFix** [comment]
Anyone?

**Comment by AviFix** [comment]
Hi,

In this file:
org.chromium.chrome.browser.FileProviderHelper

On line 25:

Changing "context.getPackageName()" to "org.chromium.chrome" . seems to solve the problem

Avi

**Comment by JackyAndroid** [comment]
Fixed
