### ISSUE TITLE
Android 4.4 ClassNotFoundException 

### ISSUE THREAD

**Issue by lyqaiym** [JackyAndroid/AndroidChromium#40]
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.chromium.chrome.browser.provider.ChromeBrowserProvider" on path: DexPathList[[zip file "/data/app/org.chromium.chrome.browser-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.chromium.chrome.browser-1, /vendor/lib, /system/lib]]
                                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                               at android.app.ActivityThread.installProvider(ActivityThread.java:4877)
                                                                               at android.app.ActivityThread.installContentProviders(ActivityThread.java:4484) 
                                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4424) 
                                                                               at android.app.ActivityThread.access$1500(ActivityThread.java:143) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:136) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5120) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)

**Comment by JackyAndroid** [comment]
duplicate #7

**Comment by lyqaiym** [comment]
I know, but it's off

**Comment by JackyAndroid** [comment]
@lyqaiym If it is a special model caused by the problem, will enhance compatibility later

**Comment by lyqaiym** [comment]
multiDex  classes2.dex classes.dex
