### ISSUE TITLE
Unable to get provider org.chromium.chrome.browser.provider.ChromeBrowserProvider

### ISSUE THREAD

**Issue by ZhangKuixun** [JackyAndroid/AndroidChromium#44]
11-03 21:47:31.124 6958-6958/org.chromium.chrome.browser E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: org.chromium.chrome.browser, PID: 6958
                                                                           java.lang.RuntimeException: Unable to get provider org.chromium.chrome.browser.provider.ChromeBrowserProvider: java.lang.ClassNotFoundException: Didn't find class "org.chromium.chrome.browser.provider.ChromeBrowserProvider" on path: DexPathList[[zip file "/data/app/org.chromium.chrome.browser-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.chromium.chrome.browser-1, /vendor/lib, /system/lib]]
                                                                               at android.app.ActivityThread.installProvider(ActivityThread.java:5011)
                                                                               at android.app.ActivityThread.installContentProviders(ActivityThread.java:4582)
                                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4515)
                                                                               at android.app.ActivityThread.access$1500(ActivityThread.java:154)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1387)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                               at android.os.Looper.loop(Looper.java:193)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:655)
                                                                               at dalvik.system.NativeStart.main(Native Method)
                                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "org.chromium.chrome.browser.provider.ChromeBrowserProvider" on path: DexPathList[[zip file "/data/app/org.chromium.chrome.browser-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.chromium.chrome.browser-1, /vendor/lib, /system/lib]]
                                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                               at android.app.ActivityThread.installProvider(ActivityThread.java:4996)
                                                                               at android.app.ActivityThread.installContentProviders(ActivityThread.java:4582) 
                                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4515) 
                                                                               at android.app.ActivityThread.access$1500(ActivityThread.java:154) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1387) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                               at android.os.Looper.loop(Looper.java:193) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5294) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:655) 
                                                                               at dalvik.system.NativeStart.main(Native Method)

**Comment by JackyAndroid** [comment]
@ZhangKuixun 请确认是否开启了instant run
