### ISSUE TITLE
 Error inserting uid=0 package_name=org.chromium.chrome.browser                                                                       android.database.sqlite.SQLiteConstraintException: columns uid, package_name are not unique (code 19)

### ISSUE THREAD

**Issue by ZhangKuixun** [JackyAndroid/AndroidChromium#45]
11-04 15:13:38.431 792-792/com.google.process.gapps E/SQLiteDatabase: Error inserting uid=0 package_name=org.chromium.chrome.browser
                                                                      android.database.sqlite.SQLiteConstraintException: columns uid, package_name are not unique (code 19)
                                                                          at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                          at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
                                                                          at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                                                                          at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                                          at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1469)
                                                                          at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1339)
                                                                          at com.google.android.gms.gcm.GcmPackageChimeraTracker.a(:com.google.android.gms:1491)
                                                                          at com.google.android.gms.gcm.GcmPackageChimeraTracker$GcmPackageChangeReceiver.onReceive(:com.google.android.gms:3394)
                                                                          at bvh.onReceive(:com.google.android.gms:235)
                                                                          at hjw.onReceive(:com.google.android.gms:62)
                                                                          at android.app.ActivityThread.handleReceiver(ActivityThread.java:2417)
                                                                          at android.app.ActivityThread.access$1700(ActivityThread.java:135)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5019)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by JackyAndroid** [comment]
@ZhangKuixun 包名可能和gradle 的 appid不一致，可以自己改下
