### ISSUE TITLE
it is Unable to start on android4.4.2

### ISSUE THREAD

**Issue by huge818** [JackyAndroid/AndroidChromium#48]
it is Unable to start on android4.4.2

**Comment by JackyAndroid** [comment]
#31 #44 Please provide more information

**Comment by huge818** [comment]
I build  a apk file，run it on android4.4.2, 
EMUI
CHM-TL00H
version

![image](https://user-images.githubusercontent.com/2882139/33256459-14fd9cde-d38d-11e7-9c1d-e40057ae7703.png)

**Comment by JackyAndroid** [comment]
@huge818 Detailed log information

**Comment by huge818** [comment]
hardware rk3188
there is no gms framework
Android 4.4.2

when i visit a website ，the debug information is that:

11-27 16:34:12.950 6159-6159/org.chromium.chrome.browser E/dalvikvm: Could not find class 'org.chromium.net.NetworkChangeNotifierAutoDetect$MyNetworkCallback', referenced from method org.chromium.net.NetworkChangeNotifierAutoDetect.<init>
11-27 16:34:12.950 6159-6159/org.chromium.chrome.browser E/dalvikvm: Could not find class 'android.net.Network[]', referenced from method org.chromium.net.NetworkChangeNotifierAutoDetect.getAllNetworksFiltered
11-27 16:34:13.140 6215-6229/org.chromium.chrome.browser:privileged_process0 E/libEGL: validate_display:254 error 3008 (EGL_BAD_DISPLAY)
11-27 16:34:13.280 6159-6159/org.chromium.chrome.browser E/dalvikvm: Could not find class 'org.chromium.content.browser.FloatingActionModeCallback', referenced from method org.chromium.content.browser.SelectionPopupController.startFloatingActionMode
11-27 16:34:13.510 6215-6229/org.chromium.chrome.browser:privileged_process0 E/chromium: [ERROR:gl_surface_egl.cc(222)] eglChooseConfig failed with error EGL_BAD_ATTRIBUTE
11-27 16:34:13.510 6215-6229/org.chromium.chrome.browser:privileged_process0 E/chromium: [ERROR:gl_surface_egl.cc(222)] eglChooseConfig failed with error EGL_BAD_ATTRIBUTE
11-27 16:34:14.110 6246-6246/? E/MultiDex: Failed to create dir /data/data/org.chromium.chrome.browser/code_cache/secondary-dexes. parent file is a dir true, a file false, exists true, readable false, writable false
11-27 16:34:14.110 6246-6246/? E/MultiDex: Multidex installation failure
                                           java.io.IOException: Failed to create cache directory /data/data/org.chromium.chrome.browser/code_cache/secondary-dexes
                                               at android.support.multidex.MultiDexExtractor.mkdirChecked(MultiDexExtractor.java:301)
                                               at android.support.multidex.MultiDexExtractor.prepareDexDir(MultiDexExtractor.java:261)
                                               at android.support.multidex.MultiDexExtractor.performExtractions(MultiDexExtractor.java:170)
                                               at android.support.multidex.MultiDexExtractor.load(MultiDexExtractor.java:102)
                                               at android.support.multidex.MultiDex.install(MultiDex.java:159)
                                               at org.chromium.chrome.browser.ChromeApplication.attachBaseContext(ChromeApplication.java:89)
                                               at android.app.Application.attach(Application.java:181)
                                               at android.app.Instrumentation.newApplication(Instrumentation.java:991)
                                               at android.app.Instrumentation.newApplication(Instrumentation.java:975)
                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4317)
                                               at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                               at android.os.Looper.loop(Looper.java:136)
                                               at android.app.ActivityThread.main(ActivityThread.java:5017)
                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                               at dalvik.system.NativeStart.main(Native Method)
11-27 16:34:14.110 6246-6246/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: org.chromium.chrome.browser:sandboxed_process1, PID: 6246
                                                 java.lang.RuntimeException: Unable to instantiate application org.chromium.chrome.browser.ChromeApplication: java.lang.RuntimeException: Multi dex installation failed (Failed to create cache directory /data/data/org.chromium.chrome.browser/code_cache/secondary-dexes).
                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:516)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4317)
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.RuntimeException: Multi dex installation failed (Failed to create cache directory /data/data/org.chromium.chrome.browser/code_cache/secondary-dexes).
                                                     at android.support.multidex.MultiDex.install(MultiDex.java:178)
                                                     at org.chromium.chrome.browser.ChromeApplication.attachBaseContext(ChromeApplication.java:89)
                                                     at android.app.Application.attach(Application.java:181)
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:991)
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:975)
                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4317)
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                     at dalvik.system.NativeStart.main(Native Method)
11-27 16:34:14.270 6159-6159/org.chromium.chrome.browser E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method org.chromium.ui.widget.ButtonCompat.updateButtonBackgroundL

**Comment by JackyAndroid** [comment]
@huge818 Is there a problem with version 4.4.2? Are there any attempts at other versions? I take time to find out the relevant model to resume the problem

**Comment by uplusplus** [comment]
error log:

11-29 10:32:47.850 32420-32420/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: org.chromium.chrome.browser:sandboxed_process1, PID: 32420
                                                   java.lang.RuntimeException: Unable to instantiate application org.chromium.chrome.browser.ChromeApplication: java.lang.RuntimeException: Multi dex installation failed (Failed to create cache directory /data/data/org.chromium.chrome.browser/code_cache/secondary-dexes).

**Comment by nickcarterney** [comment]
@JackyAndroid Did you solve this issue?

**Comment by JackyAndroid** [comment]
@nickcartery cannot  resume the problem
