### ISSUE TITLE
6.0启动闪退

### ISSUE THREAD

**Issue by lailiaomm** [JackyAndroid/AndroidChromium#5]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: org.chromium.chrome.browser, PID: 12011
                                                                             java.lang.RuntimeException: Unable to get provider org.chromium.chrome.browser.ChromeBrowserProvider: java.lang.ClassCastException: com.android.tools.fd.runtime.BootstrapApplication cannot be cast to org.chromium.base.BaseChromiumApplication
                                                                                 at android.app.ActivityThread.installProvider(ActivityThread.java:5156)
                                                                                 at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748)
                                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688)
                                                                                 at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                              Caused by: java.lang.ClassCastException: com.android.tools.fd.runtime.BootstrapApplication cannot be cast to org.chromium.base.BaseChromiumApplication
                                                                                 at org.chromium.base.BaseChromiumApplication.initCommandLine(BaseChromiumApplication.java:76)
                                                                                 at org.chromium.chrome.browser.ChromeBrowserProvider.onCreate(ChromeBrowserProvider.java:267)
                                                                                 at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
                                                                                 at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
                                                                                 at android.app.ActivityThread.installProvider(ActivityThread.java:5153)
                                                                                 at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748) 
                                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688) 
                                                                                 at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by lailiaomm** [comment]
已经解决了。。美观Instant run导致的
