### ISSUE TITLE
android6.0报错了

### ISSUE THREAD

**Issue by ahe168** [JackyAndroid/AndroidChromium#75]
05-17 07:53:44.571 18430-18457/org.chromium.chrome.browser E/cr_ChromiumAndroidLinker: GetLibraryLoadSize: Failed to find library at address 0x85840000
05-17 07:53:44.572 18430-18457/org.chromium.chrome.browser E/cr_ChromiumAndroidLinker: LoadLibrary: Unable to find size for load at 0x85840000
05-17 07:53:44.572 18430-18457/org.chromium.chrome.browser E/cr_LibraryLoader: Unable to load library: libchrome.so
05-17 07:53:44.572 18430-18457/org.chromium.chrome.browser E/NativeInitializationController: Unable to load native library.
    org.chromium.base.library_loader.ProcessInitException
        at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:325)
        at org.chromium.base.library_loader.LibraryLoader.ensureInitialized(LibraryLoader.java:142)
        at org.chromium.chrome.browser.init.NativeInitializationController$2.run(NativeInitializationController.java:122)
     Caused by: java.lang.UnsatisfiedLinkError: Unable to load library: libchrome.so
        at org.chromium.base.library_loader.ModernLinker.loadLibraryImpl(ModernLinker.java:415)
        at org.chromium.base.library_loader.Linker.loadLibrary(Linker.java:569)
        at org.chromium.base.library_loader.LibraryLoader.loadLibrary(LibraryLoader.java:254)
        at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:301)
        at org.chromium.base.library_loader.LibraryLoader.ensureInitialized(LibraryLoader.java:142) 
        at org.chromium.chrome.browser.init.NativeInitializationController$2.run(NativeInitializationController.java:122)

**Comment by JackyAndroid** [comment]
运行的手机是什么abi？
